spring:
  data:
    mongodb:
      uri: mongodb://microservices:0000@mongodb:27017/microservices
  zipkin:
    baseUrl: http://192.168.99.1:9411 
api:
  claimClientName: http://wso2.org/claims/enduser
